#!/bin/bash
echjo "post-merge"
d1=$PWD
del=$(git status -b)
dels=(${del// / })
delsa=${dels[2]}

if test "$delsa" = "master"
then
cd CasosAcadAppMvn
mvn package
else
echo "No es master. así que no se va a construir el maven"
 fi
cd $d
